version: 1.2.0.{build}
branches:
  only:
  - master
pull_requests:
  do_not_increment_build_number: true
environment:
  COVERALLS_REPO_TOKEN:
    secure: 7AjpkjtpN2vWJAJM38Hyz30vl/HP+OQLTJun79ZhCyBx8L4G/W4VJZ+w/vijLuHd
  COVER_FILTER: '+[Equalizer*]* -[*]*.Logging.* -[*Tests]*'
install:
  - ps: .\build\install.ps1
build_script:
- ps: .\build\build.ps1 $env:APPVEYOR_BUILD_VERSION $env:APPVEYOR_REPO_TAG_NAME
test_script:
- ps: |
    if ($true)
    {
        Invoke-Expression ".\build\test.ps1"
        Invoke-Expression ".\build\cover.ps1 $env:COVERALLS_REPO_TOKEN $env:COVER_FILTER"
    }
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: Uft/AgWL0ObDUb6hWLhsftRR1sNhLa5vONUcVa/2KjVAYZApxZD6ckJ+ABFQs3bB
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only
